<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net462</TargetFramework>
		<UseWPF>true</UseWPF>
		<LangVersion>8.0</LangVersion>
		<Platforms>x86</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="TransportInformation.db" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="TransportInformation.db">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="SourceGear.sqlite3" Version="3.53.4" />
	  <PackageReference Include="System.Data.SQLite" Version="2.0.4" />

		
	</ItemGroup>

</Project>